esphome:
  name: dual-net-webble

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: debug

binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "Button"
    id: button
    internal: false
    on_press:
     then:
       - logger.log: "Button wurde gedrückt!"

